version: "3.9"

services:
    todo-app-with-java-gradle:
        container_name: todo-app-with-java-gradle
        build:
            context: ./docker
        tty: true
        volumes:
            - ../:/home/vscode/workspace:cache
        ports:
            - 8080:8080
        depends_on:
            - db

    # dev用データベース
    db:
        image: postgres:latest
        container_name: db
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: "dev" # = DB名
            POSTGRES_PASSWORD: "pass"
        volumes:
            - ./init_db:/docker-entrypoint-initdb.d

    # Webベースのデータベース管理ツール
    adminer:
        image: adminer:4.8.1
        container_name: adminer
        ports:
            - "9000:8080"
        depends_on:
            - db
