# Workflowの名前
name: Build and Test on Push

# Workflowを動かすトリガー（=Event）を指定
# pushをEventに設定
on:
  - push

jobs:
  # build job
  build:
    # Runnerを指定
    runs-on: ubuntu-latest
    # Step
    steps:
      # RunnnerにGitリポジトリのコピーをダウンロード
      - uses: actions/checkout@v3
      # Java 17をセットアップ
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      # Test実行
      - name: Run tests
        run: ./gradlew test
