name: Build and Test on Push

# pushをEventに設定
on:
  - push

jobs:
  build:
    # Runnerを指定
    runs-on: ubuntu-latest
    
    services:
      # PostgreSQLのサービスを定義
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }} # PostgreSQLのデータベース名
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }} # PostgreSQLのユーザー名
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} # PostgreSQLのパスワード
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: jdbc:postgresql://localhost:5432/${{ secrets.POSTGRES_DB }} # テスト時に使用するPostgreSQLの接続URL

    steps:
    # RunnnerにGitリポジトリのコピーをダウンロード
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Java 17をセットアップ
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    # PostgreSQLの起動を待機
    - name: Wait for PostgreSQL to start
      run: dockerize -wait tcp://localhost:5432 -timeout 1m

    # PostgreSQLにpgcrypto拡張機能を作成
    - name: Create extension pgcrypto
      run: docker exec -i ${{ job.services.postgres.id }} psql -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

    # Build
    - name: Build with Gradle
      run: ./gradlew build
      
    # Test実行
    - name: Run tests
      run: ./gradlew test
